// ui/src/routes/schema.tsx
import { createRoute, useNavigate, useSearch } from '@tanstack/react-router'
import { useState, useEffect, useMemo } from 'react'
import { Markdown } from '../components/Markdown'
import { InlineMarkdown } from '../components/InlineMarkdown'
import { getSchema, type SchemaResponse } from '../lib/api'
import { formatSchemaType, parseSchemaTypeString } from '../lib/schemaType'
import { Route as RootRoute } from './__root'

type SchemaSearch = {
  schema?: string
  type?: string
}

export const Route = createRoute({
  getParentRoute: () => RootRoute,
  path: 'schema',
  component: Schema,
})

function Schema() {
  const navigate = useNavigate()
  const search = useSearch({ from: '/schema' })

  const [schema, setSchema] = useState<SchemaResponse | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [selectedDefinition, setSelectedDefinition] = useState<string | null>(null)
  const [showRoot, setShowRoot] = useState(true)

  useEffect(() => {
    async function fetchSchema() {
      setLoading(true)
      setError(null)

      const schemaParam = search.schema || 'ForgeRegistryV2'

      try {
        const data = await getSchema(schemaParam)
        setSchema(data)
      } catch (e) {
        setError(e instanceof Error ? e.message : 'Unknown error')
      } finally {
        setLoading(false)
      }
    }

    fetchSchema()
  }, [search.schema])

  useEffect(() => {
    const typeParam = search.type
    if (typeParam === 'root' || !typeParam) {
      setShowRoot(true)
      setSelectedDefinition(null)
    } else {
      setShowRoot(false)
      setSelectedDefinition(typeParam)
    }
  }, [search.type])

  const definitions = useMemo(() => {
    if (!schema?.$defs) return []
    const defs = schema.$defs
    return Object.keys(defs).sort()
  }, [schema])

  function selectDefinition(name: string) {
    navigate({
      to: '/schema',
      search: (prev: SchemaSearch) => ({
        ...prev,
        type: name,
        schema: prev.schema || 'ForgeRegistryV2'
      })
    })
  }

  function selectRoot() {
    navigate({
      to: '/schema',
      search: (prev: SchemaSearch) => ({
        ...prev,
        type: 'root',
        schema: prev.schema || 'ForgeRegistryV2'
      })
    })
  }

  function isDefinitionRef(typeStr: string): boolean {
    if (!typeStr || typeStr === 'unknown') return false
    const simpleTypes = ['string', 'number', 'boolean', 'object', 'array', 'null', 'integer', 'any']
    if (simpleTypes.includes(typeStr)) return false
    if (typeStr.startsWith('array of ')) return false
    if (typeStr.startsWith('map of ')) return false
    if (typeStr.includes(' | ')) return false
    const defs = schema?.$defs || {}
    return defs[typeStr] !== undefined
  }

  return (
    <div className="flex gap-4 h-[calc(100vh-4rem)]">
      <div className="w-80 border-r border-base-300 overflow-y-auto pr-4">
        {loading ? (
          <div className="flex justify-center py-8">
            <span className="loading loading-spinner loading-lg"></span>
          </div>
        ) : error ? (
          <div className="alert alert-error" role="alert">
            <span>Error: {error}</span>
          </div>
        ) : schema ? (
          <div className="space-y-4">
            <button
              onClick={() => selectRoot()}
              className={`card sticky top-0 z-10 w-full text-left transition-colors cursor-pointer ${
                showRoot ? 'bg-primary text-primary-content' : 'bg-base-200 hover:bg-base-300'
              }`}
            >
              <div className="card-body p-4">
                <h1 className="font-bold text-xl">{schema.title || 'Schema'}</h1>
                <p className="text-sm opacity-70">{schema.description || ''}</p>
              </div>
            </button>

            <div>
              <h3 className="font-bold text-sm mb-2 text-base-content/70">
                TYPE DEFINITIONS ({definitions.length})
              </h3>
              <div className="space-y-1">
                {definitions.map(def => (
                  <button
                    key={def}
                    onClick={() => selectDefinition(def)}
                    className={`w-full text-left px-3 py-2 rounded transition-colors text-sm ${
                      selectedDefinition === def
                        ? 'bg-primary text-primary-content'
                        : 'hover:bg-base-200'
                    }`}
                  >
                    <code className="font-mono">{def}</code>
                  </button>
                ))}
              </div>
            </div>
          </div>
        ) : null}
      </div>

      <div className="flex-1 overflow-y-auto">
        {showRoot && schema && (schema.properties || schema.oneOf || schema.anyOf) ? (
          <div className="space-y-6">
            <div>
              <h2 className="text-2xl font-mono font-bold mb-2">Root</h2>
              {schema.description ? (
                <div className="text-base-content/70">
                  <Markdown content={schema.description} />
                </div>
              ) : (
                <div className="text-base-content/70">
                  <p>Top-level properties of schema</p>
                </div>
              )}
              <div className="mt-2">
                {schema.type ? (
                  <span className="badge badge-outline">{schema.type}</span>
                ) : schema.oneOf ? (
                  <span className="badge badge-outline">oneOf</span>
                ) : schema.anyOf ? (
                  <span className="badge badge-outline">anyOf</span>
                ) : null}
              </div>
            </div>

            {(schema.oneOf || schema.anyOf) && (
              <div>
                <h3 className="text-lg font-bold mb-3">{schema.oneOf ? 'One Of' : 'Any Of'}</h3>
                <div className="space-y-2">
                  {(schema.oneOf || schema.anyOf)!.map((variant, idx) => {
                    const variantType = formatSchemaType(variant)
                    const variantParts = parseSchemaTypeString(variantType, isDefinitionRef)
                    return (
                      <div key={idx} className="card bg-base-200">
                        <div className="card-body p-4">
                          {variant.enum && variant.enum.length === 1 ? (
                            <code className="badge badge-outline font-mono">{String(variant.enum[0])}</code>
                          ) : variant.type === 'object' && variant.properties ? (
                            <span className="badge badge-outline font-mono">object</span>
                          ) : (
                            <span className="badge badge-outline font-mono inline-flex items-center gap-1">
                              {variantParts.map((part, i) => (
                                <span key={i}>
                                  {part.isClickable ? (
                                    <button
                                      className="hover:text-primary cursor-pointer underline"
                                      onClick={() => selectDefinition(part.text)}
                                    >
                                      {part.text}
                                    </button>
                                  ) : (
                                    <span>{part.text}</span>
                                  )}
                                </span>
                              ))}
                            </span>
                          )}
                          {variant.description && (
                            <div className="text-sm mt-2">
                              <Markdown content={variant.description} />
                            </div>
                          )}

                          {variant.type === 'object' && variant.properties && (
                            <div className="mt-3">
                              <table className="table table-xs">
                                <thead>
                                  <tr>
                                    <th>Field</th>
                                    <th>Type</th>
                                    <th>Required</th>
                                    <th>Description</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  {Object.entries(variant.properties).map(([propName, propDef]) => {
                                    const isRequired = variant.required?.includes(propName)
                                    const typeStr = formatSchemaType(propDef, !isRequired)
                                    const typeParts = parseSchemaTypeString(typeStr, isDefinitionRef)
                                    return (
                                      <tr key={propName}>
                                        <td>
                                          <code className="font-mono text-xs">{propName}</code>
                                        </td>
                                        <td>
                                          <span className="badge badge-xs badge-outline font-mono inline-flex items-center gap-1">
                                            {typeParts.map((part, i) => (
                                              <span key={i}>
                                                {part.isClickable ? (
                                                  <button
                                                    className="hover:text-primary cursor-pointer underline"
                                                    onClick={() => selectDefinition(part.text)}
                                                  >
                                                    {part.text}
                                                  </button>
                                                ) : (
                                                  <span>{part.text}</span>
                                                )}
                                              </span>
                                            ))}
                                          </span>
                                          {propDef.enum && (
                                            <div className="flex flex-wrap gap-1 mt-1">
                                              {propDef.enum.map(enumVal => (
                                                <code key={String(enumVal)} className="badge badge-xs">
                                                  {String(enumVal)}
                                                </code>
                                              ))}
                                            </div>
                                          )}
                                        </td>
                                        <td>
                                          {isRequired ? (
                                            <span className="badge badge-xs badge-error">required</span>
                                          ) : (
                                            <span className="badge badge-xs badge-ghost">optional</span>
                                          )}
                                        </td>
                                        <td className="text-xs">
                                          {propDef.description ? (
                                            <InlineMarkdown content={propDef.description} />
                                          ) : (
                                            '-'
                                          )}
                                        </td>
                                      </tr>
                                    )
                                  })}
                                </tbody>
                              </table>
                            </div>
                          )}
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>
            )}

            {schema.properties && schema.required && schema.required.length > 0 && (
              <div>
                <h3 className="text-lg font-bold mb-3">Required Fields</h3>
                <div className="flex flex-wrap gap-2">
                  {schema.required.map(field => (
                    <span key={field} className="badge badge-error">{field}</span>
                  ))}
                </div>
              </div>
            )}

            {schema.properties && (
              <div>
                <h3 className="text-lg font-bold mb-3">Properties</h3>
                <div className="overflow-x-auto">
                  <table className="table table-zebra">
                    <thead>
                      <tr>
                        <th>Field</th>
                        <th>Type</th>
                        <th>Required</th>
                        <th>Description</th>
                      </tr>
                    </thead>
                    <tbody>
                      {Object.entries(schema.properties).map(([propName, propDef]) => {
                        const isRequired = schema.required?.includes(propName)
                        const typeStr = formatSchemaType(propDef, !isRequired)
                        const typeParts = parseSchemaTypeString(typeStr, isDefinitionRef)
                        return (
                          <tr key={propName}>
                            <td>
                              <code className="font-mono text-sm">{propName}</code>
                            </td>
                            <td>
                              <span className="badge badge-sm badge-outline font-mono inline-flex items-center gap-1">
                                {typeParts.map((part, i) => (
                                  <span key={i}>
                                    {part.isClickable ? (
                                      <button
                                        className="hover:text-primary cursor-pointer underline"
                                        onClick={() => selectDefinition(part.text)}
                                      >
                                        {part.text}
                                      </button>
                                    ) : (
                                      <span>{part.text}</span>
                                    )}
                                  </span>
                                ))}
                              </span>
                            </td>
                            <td>
                              {isRequired ? (
                                <span className="badge badge-sm badge-error">required</span>
                              ) : (
                                <span className="badge badge-sm badge-ghost">optional</span>
                              )}
                            </td>
                            <td className="text-sm max-w-md">
                              {propDef.description ? (
                                <InlineMarkdown content={propDef.description} />
                              ) : (
                                '-'
                              )}
                            </td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            <div>
              <h3 className="text-lg font-bold mb-3">Raw JSON</h3>
              <div className="mockup-code bg-base-300">
                <pre className="text-xs overflow-x-auto text-base-content">
                  <code>
                    {JSON.stringify(
                      schema.properties
                        ? {
                            type: 'object',
                            properties: schema.properties,
                            required: schema.required,
                          }
                        : schema,
                      null,
                      2
                    )}
                  </code>
                </pre>
              </div>
            </div>
          </div>
        ) : selectedDefinition && ((schema?.$defs || {})[selectedDefinition]) ? (
          (() => {
            const def = (schema.$defs || {})[selectedDefinition]
            return (
              <div className="space-y-6">
                <div>
                  <h2 className="text-2xl font-mono font-bold mb-2">{selectedDefinition}</h2>
                  {def.description && (
                    <div className="text-base-content/70">
                      <Markdown content={def.description} />
                    </div>
                  )}
                  {def.type && (
                    <div className="mt-2">
                      <span className="badge badge-outline">{def.type}</span>
                    </div>
                  )}
                </div>

                {def.required && def.required.length > 0 && (
                  <div>
                    <h3 className="text-lg font-bold mb-3">Required Fields</h3>
                    <div className="flex flex-wrap gap-2">
                      {def.required.map(field => (
                        <span key={field} className="badge badge-error">{field}</span>
                      ))}
                    </div>
                  </div>
                )}

                {def.properties && (
                  <div>
                    <h3 className="text-lg font-bold mb-3">Properties</h3>
                    <div className="overflow-x-auto">
                      <table className="table table-zebra">
                        <thead>
                          <tr>
                            <th>Field</th>
                            <th>Type</th>
                            <th>Required</th>
                            <th>Description</th>
                          </tr>
                        </thead>
                        <tbody>
                          {Object.entries(def.properties).map(([propName, propDef]) => {
                            const isRequired = def.required?.includes(propName)
                            const typeStr = formatSchemaType(propDef, !isRequired)
                            const typeParts = parseSchemaTypeString(typeStr, isDefinitionRef)
                            return (
                              <tr key={propName}>
                                <td>
                                  <code className="font-mono text-sm">{propName}</code>
                                </td>
                                <td>
                                  <span className="badge badge-sm badge-outline font-mono inline-flex items-center gap-1">
                                    {typeParts.map((part, i) => (
                                      <span key={i}>
                                        {part.isClickable ? (
                                          <button
                                            className="hover:text-primary cursor-pointer underline"
                                            onClick={() => selectDefinition(part.text)}
                                          >
                                            {part.text}
                                          </button>
                                        ) : (
                                          <span>{part.text}</span>
                                        )}
                                      </span>
                                    ))}
                                  </span>
                                </td>
                                <td>
                                  {isRequired ? (
                                    <span className="badge badge-sm badge-error">required</span>
                                  ) : (
                                    <span className="badge badge-sm badge-ghost">optional</span>
                                  )}
                                </td>
                                <td className="text-sm max-w-md">
                                  {propDef.description ? (
                                    <InlineMarkdown content={propDef.description} />
                                  ) : (
                                    '-'
                                  )}
                                </td>
                              </tr>
                            )
                          })}
                        </tbody>
                      </table>
                    </div>
                  </div>
                )}

                {def.enum && (
                  <div>
                    <h3 className="text-lg font-bold mb-3">Allowed Values</h3>
                    <div className="flex flex-wrap gap-2">
                      {def.enum.map(value => (
                        <code key={String(value)} className="badge badge-lg font-mono">
                          {String(value)}
                        </code>
                      ))}
                    </div>
                  </div>
                )}

                {(def.oneOf || def.anyOf) && (
                  <div>
                    <h3 className="text-lg font-bold mb-3">{def.oneOf ? 'One Of' : 'Any Of'}</h3>
                    <div className="space-y-2">
                      {(def.oneOf || def.anyOf)!.map((variant, idx) => {
                        const variantType = formatSchemaType(variant)
                        const variantParts = parseSchemaTypeString(variantType, isDefinitionRef)
                        return (
                          <div key={idx} className="card bg-base-200">
                            <div className="card-body p-4">
                              {variant.enum && variant.enum.length === 1 ? (
                                <code className="badge badge-outline font-mono">{String(variant.enum[0])}</code>
                              ) : variant.type === 'object' && variant.properties ? (
                                <span className="badge badge-outline font-mono">object</span>
                              ) : (
                                <span className="badge badge-outline font-mono inline-flex items-center gap-1">
                                  {variantParts.map((part, i) => (
                                    <span key={i}>
                                      {part.isClickable ? (
                                        <button
                                          className="hover:text-primary cursor-pointer underline"
                                          onClick={() => selectDefinition(part.text)}
                                        >
                                          {part.text}
                                        </button>
                                      ) : (
                                        <span>{part.text}</span>
                                      )}
                                    </span>
                                  ))}
                                </span>
                              )}
                              {variant.description && (
                                <div className="text-sm mt-2">
                                  <Markdown content={variant.description} />
                                </div>
                              )}

                              {variant.type === 'object' && variant.properties && (
                                <div className="mt-3">
                                  <table className="table table-xs">
                                    <thead>
                                      <tr>
                                        <th>Field</th>
                                        <th>Type</th>
                                        <th>Required</th>
                                        <th>Description</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      {Object.entries(variant.properties).map(([propName, propDef]) => {
                                        const isRequired = variant.required?.includes(propName)
                                        const typeStr = formatSchemaType(propDef, !isRequired)
                                        const typeParts = parseSchemaTypeString(typeStr, isDefinitionRef)
                                        return (
                                          <tr key={propName}>
                                            <td>
                                              <code className="font-mono text-xs">{propName}</code>
                                            </td>
                                            <td>
                                              <span className="badge badge-xs badge-outline font-mono inline-flex items-center gap-1">
                                                {typeParts.map((part, i) => (
                                                  <span key={i}>
                                                    {part.isClickable ? (
                                                      <button
                                                        className="hover:text-primary cursor-pointer underline"
                                                        onClick={() => selectDefinition(part.text)}
                                                      >
                                                        {part.text}
                                                      </button>
                                                    ) : (
                                                      <span>{part.text}</span>
                                                    )}
                                                  </span>
                                                ))}
                                              </span>
                                              {propDef.enum && (
                                                <div className="flex flex-wrap gap-1 mt-1">
                                                  {propDef.enum.map(enumVal => (
                                                    <code key={String(enumVal)} className="badge badge-xs">
                                                      {String(enumVal)}
                                                    </code>
                                                  ))}
                                                </div>
                                              )}
                                            </td>
                                            <td>
                                              {isRequired ? (
                                                <span className="badge badge-xs badge-error">required</span>
                                              ) : (
                                                <span className="badge badge-xs badge-ghost">optional</span>
                                              )}
                                            </td>
                                            <td className="text-xs">
                                              {propDef.description ? (
                                                <InlineMarkdown content={propDef.description} />
                                              ) : (
                                                '-'
                                              )}
                                            </td>
                                          </tr>
                                        )
                                      })}
                                    </tbody>
                                  </table>
                                </div>
                              )}
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  </div>
                )}

                <div>
                  <h3 className="text-lg font-bold mb-3">Raw JSON</h3>
                  <div className="mockup-code bg-base-300">
                    <pre className="text-xs overflow-x-auto text-base-content">
                      <code>{JSON.stringify(def, null, 2)}</code>
                    </pre>
                  </div>
                </div>
              </div>
            )
          })()
        ) : (
          <div className="flex items-center justify-center h-full text-base-content/50">
            <div className="text-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              <p className="text-lg">Select a type definition to view details</p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

// ui/src/routes/Schema.svelte
<script>
  let schema = $state(null);
  let error = $state(null);
  let loading = $state(true);
  let selectedDefinition = $state(null);

  // Fetch schema on mount
  $effect(() => {
    async function fetchSchema() {
      try {
        const response = await fetch('/api/v1/schema');
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        schema = await response.json();
      } catch (e) {
        error = e.message;
      } finally {
        loading = false;
      }
    }
    fetchSchema();
  });

  // Extract definitions from schema
  const definitions = $derived(schema?.definitions ? Object.keys(schema.definitions).sort() : []);

  function selectDefinition(name) {
    selectedDefinition = name;
  }

  function formatType(prop) {
    // Check for array with items first (before checking prop.type)
    if (prop.type === 'array' && prop.items) {
      // Handle nested arrays (array of array)
      if (prop.items.type === 'array' && prop.items.items) {
        const innerType = prop.items.items.$ref
          ? prop.items.items.$ref.replace('#/definitions/', '')
          : prop.items.items.type || 'any';
        return `array of array of ${innerType}`;
      }
      // Handle simple arrays
      const itemType = prop.items.$ref
        ? prop.items.$ref.replace('#/definitions/', '')
        : prop.items.type || 'any';
      return `array of ${itemType}`;
    }

    if (Array.isArray(prop.type)) {
      return prop.type.join(' | ');
    }
    if (prop.type) return prop.type;
    if (prop.$ref) return prop.$ref.replace('#/definitions/', '');
    if (prop.allOf) {
      // allOf is typically used for single type references
      if (prop.allOf.length === 1 && prop.allOf[0].$ref) {
        return prop.allOf[0].$ref.replace('#/definitions/', '');
      }
      return prop.allOf.map(t => t.$ref ? t.$ref.replace('#/definitions/', '') : t.type || 'object').join(' & ');
    }
    if (prop.anyOf) {
      return prop.anyOf.map(t => t.$ref ? t.$ref.replace('#/definitions/', '') : t.type || 'null').join(' | ');
    }
    if (prop.oneOf) {
      return prop.oneOf.map(t => t.$ref ? t.$ref.replace('#/definitions/', '') : t.type || 'null').join(' | ');
    }
    return 'unknown';
  }

  // Check if a type string is a reference to a definition
  function isDefinitionRef(typeStr) {
    if (!typeStr || typeStr === 'unknown') return false;
    // Check if it's a simple type
    const simpleTypes = ['string', 'number', 'boolean', 'object', 'array', 'null', 'integer', 'any'];
    if (simpleTypes.includes(typeStr)) return false;
    // Check if it starts with "array of " (array type)
    if (typeStr.startsWith('array of ')) return false;
    // Check if it contains " | " (union type)
    if (typeStr.includes(' | ')) return false;
    // Otherwise, it's likely a definition reference
    return schema?.definitions && schema.definitions[typeStr] !== undefined;
  }

  // Parse a type string and return clickable parts
  function parseTypeString(typeStr) {
    if (!typeStr) return [];

    // Handle union types (e.g., "Stability | null")
    if (typeStr.includes(' | ')) {
      return typeStr.split(' | ').map(part => ({
        text: part,
        isClickable: isDefinitionRef(part.trim())
      }));
    }

    // Handle nested array types (e.g., "array of array of integer")
    if (typeStr.startsWith('array of array of ')) {
      const innerType = typeStr.slice(18); // Skip "array of array of "
      return [
        { text: 'array of array of ', isClickable: false },
        { text: innerType, isClickable: isDefinitionRef(innerType) }
      ];
    }

    // Handle simple array types (e.g., "array of AttributeDef")
    if (typeStr.startsWith('array of ')) {
      const innerType = typeStr.slice(9); // Skip "array of "
      return [
        { text: 'array of ', isClickable: false },
        { text: innerType, isClickable: isDefinitionRef(innerType) }
      ];
    }

    // Single type
    return [{ text: typeStr, isClickable: isDefinitionRef(typeStr) }];
  }

  // Helper to navigate to a definition from a root property
  function selectPropertyType(prop) {
    const propDef = schema.properties[prop];

    // Check for direct $ref
    if (propDef.$ref) {
      const typeName = propDef.$ref.replace('#/definitions/', '');
      selectDefinition(typeName);
      return;
    }

    // Check for allOf with $ref
    if (propDef.allOf?.length > 0 && propDef.allOf[0].$ref) {
      const typeName = propDef.allOf[0].$ref.replace('#/definitions/', '');
      selectDefinition(typeName);
      return;
    }

    // Check for array with $ref
    if (propDef.items?.$ref) {
      const typeName = propDef.items.$ref.replace('#/definitions/', '');
      selectDefinition(typeName);
      return;
    }

    // Check for anyOf with single $ref
    if (propDef.anyOf?.length === 1 && propDef.anyOf[0].$ref) {
      const typeName = propDef.anyOf[0].$ref.replace('#/definitions/', '');
      selectDefinition(typeName);
      return;
    }

    // Check for anyOf with $ref (skip null types)
    if (propDef.anyOf) {
      const refItem = propDef.anyOf.find(item => item.$ref);
      if (refItem) {
        const typeName = refItem.$ref.replace('#/definitions/', '');
        selectDefinition(typeName);
        return;
      }
    }
  }
</script>

<div class="flex gap-4 h-[calc(100vh-4rem)]">
  <!-- Left sidebar: definitions list -->
  <div class="w-80 border-r border-base-300 overflow-y-auto pr-4">
    {#if loading}
      <div class="flex justify-center py-8">
        <span class="loading loading-spinner loading-lg"></span>
      </div>
    {:else if error}
      <div class="alert alert-error">
        <span>Error: {error}</span>
      </div>
    {:else if schema}
      <div class="space-y-4">
        <!-- Schema info -->
        <div class="card bg-base-200 sticky top-0 z-10">
          <div class="card-body p-4">
            <h1 class="font-bold text-xl">{schema.title || 'Schema'}</h1>
            <p class="text-sm text-base-content/70">{schema.description || ''}</p>
          </div>
        </div>

        <!-- Top-level properties -->
        <div>
          <h3 class="font-bold text-sm mb-2 text-base-content/70">ROOT PROPERTIES</h3>
          <div class="space-y-1">
            {#each Object.keys(schema.properties || {}) as prop}
              <button
                class="w-full text-left px-3 py-2 bg-base-200 hover:bg-base-300 rounded text-sm transition-colors cursor-pointer"
                onclick={() => selectPropertyType(prop)}
              >
                <code class="font-mono">{prop}</code>
                {#if schema.properties[prop].description}
                  <p class="text-xs text-base-content/60 mt-1">{schema.properties[prop].description}</p>
                {/if}
              </button>
            {/each}
          </div>
        </div>

        <!-- Definitions -->
        <div>
          <h3 class="font-bold text-sm mb-2 text-base-content/70">TYPE DEFINITIONS ({definitions.length})</h3>
          <div class="space-y-1">
            {#each definitions as def}
              <button
                class="w-full text-left px-3 py-2 rounded transition-colors text-sm"
                class:bg-primary={selectedDefinition === def}
                class:text-primary-content={selectedDefinition === def}
                class:hover:bg-primary-focus={selectedDefinition === def}
                class:hover:bg-base-200={selectedDefinition !== def}
                onclick={() => selectDefinition(def)}
              >
                <code class="font-mono">{def}</code>
              </button>
            {/each}
          </div>
        </div>
      </div>
    {/if}
  </div>

  <!-- Right panel: definition details -->
  <div class="flex-1 overflow-y-auto">
    {#if selectedDefinition && schema?.definitions[selectedDefinition]}
      {@const def = schema.definitions[selectedDefinition]}
      <div class="space-y-6">
        <!-- Header -->
        <div>
          <h2 class="text-2xl font-mono font-bold mb-2">{selectedDefinition}</h2>
          {#if def.description}
            <p class="text-base-content/70">{def.description}</p>
          {/if}
          {#if def.type}
            <div class="mt-2">
              <span class="badge badge-outline">{def.type}</span>
            </div>
          {/if}
        </div>

        <!-- Required fields -->
        {#if def.required && def.required.length > 0}
          <div>
            <h3 class="text-lg font-bold mb-3">Required Fields</h3>
            <div class="flex flex-wrap gap-2">
              {#each def.required as field}
                <span class="badge badge-error">{field}</span>
              {/each}
            </div>
          </div>
        {/if}

        <!-- Properties -->
        {#if def.properties}
          <div>
            <h3 class="text-lg font-bold mb-3">Properties</h3>
            <div class="overflow-x-auto">
              <table class="table table-zebra">
                <thead>
                  <tr>
                    <th>Field</th>
                    <th>Type</th>
                    <th>Required</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>
                  {#each Object.entries(def.properties) as [propName, propDef]}
                    {@const typeStr = formatType(propDef)}
                    {@const typeParts = parseTypeString(typeStr)}
                    <tr>
                      <td>
                        <code class="font-mono text-sm">{propName}</code>
                      </td>
                      <td>
                        <span class="badge badge-sm badge-outline font-mono inline-flex items-center gap-1">
                          {#each typeParts as part, i}
                            {#if part.isClickable}
                              <button
                                class="hover:text-primary cursor-pointer underline"
                                onclick={() => selectDefinition(part.text)}
                              >
                                {part.text}
                              </button>
                            {:else}
                              <span>{part.text}</span>
                            {/if}
                            {#if i < typeParts.length - 1 && typeStr.includes(' | ')}
                              <span class="mx-1">|</span>
                            {/if}
                          {/each}
                        </span>
                      </td>
                      <td>
                        {#if def.required?.includes(propName)}
                          <span class="badge badge-sm badge-error">required</span>
                        {:else}
                          <span class="badge badge-sm badge-ghost">optional</span>
                        {/if}
                      </td>
                      <td class="text-sm max-w-md">{propDef.description || '-'}</td>
                    </tr>
                  {/each}
                </tbody>
              </table>
            </div>
          </div>
        {/if}

        <!-- Enum values -->
        {#if def.enum}
          <div>
            <h3 class="text-lg font-bold mb-3">Allowed Values</h3>
            <div class="flex flex-wrap gap-2">
              {#each def.enum as value}
                <code class="badge badge-lg font-mono">{value}</code>
              {/each}
            </div>
          </div>
        {/if}

        <!-- oneOf/anyOf -->
        {#if def.oneOf || def.anyOf}
          {@const variants = def.oneOf || def.anyOf}
          <div>
            <h3 class="text-lg font-bold mb-3">{def.oneOf ? 'One Of' : 'Any Of'}</h3>
            <div class="space-y-2">
              {#each variants as variant}
                {@const variantType = formatType(variant)}
                {@const variantParts = parseTypeString(variantType)}
                <div class="card bg-base-200">
                  <div class="card-body p-4">
                    <span class="badge badge-outline font-mono inline-flex items-center gap-1">
                      {#each variantParts as part}
                        {#if part.isClickable}
                          <button
                            class="hover:text-primary cursor-pointer underline"
                            onclick={() => selectDefinition(part.text)}
                          >
                            {part.text}
                          </button>
                        {:else}
                          <span>{part.text}</span>
                        {/if}
                      {/each}
                    </span>
                    {#if variant.description}
                      <p class="text-sm mt-2">{variant.description}</p>
                    {/if}
                  </div>
                </div>
              {/each}
            </div>
          </div>
        {/if}

        <!-- Raw JSON view -->
        <div>
          <h3 class="text-lg font-bold mb-3">Raw JSON</h3>
          <div class="mockup-code bg-base-300">
            <pre class="text-xs overflow-x-auto text-base-content"><code>{JSON.stringify(def, null, 2)}</code></pre>
          </div>
        </div>
      </div>
    {:else}
      <div class="flex items-center justify-center h-full text-base-content/50">
        <div class="text-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <p class="text-lg">Select a type definition to view details</p>
        </div>
      </div>
    {/if}
  </div>
</div>
