// ui/src/components/InlineMarkdown.svelte
<script>
  import { marked } from 'marked';

  let { content = '', class: className = '' } = $props();

  // Render markdown to HTML (inline) - simple approach
  function renderMarkdown(text) {
    if (!text || typeof text !== 'string') return '';

    try {
      // Use marked synchronously by accessing the default export directly
      const result = marked.parse(text, {
        async: false,
        breaks: false,
        gfm: true
      });

      // Remove paragraph tags for inline rendering
      if (typeof result === 'string') {
        return result.replace(/<\/?p>/g, '');
      }
      return '';
    } catch (e) {
      console.error('Markdown rendering error:', e);
      return text; // Fallback to plain text
    }
  }

  const html = $derived(renderMarkdown(content));
</script>

<span class={className}>{@html html}</span>

<style>
  /* Inline styles for markdown elements */
  :global(span code) {
    background-color: hsl(var(--b3));
    padding: 0.125rem 0.25rem;
    border-radius: 0.25rem;
    font-size: 0.875em;
  }
  :global(span a) {
    color: hsl(var(--p));
    text-decoration: underline;
  }
  :global(span strong) {
    font-weight: 600;
  }
  :global(span em) {
    font-style: italic;
  }
</style>

// ui/src/components/InlineMarkdown.tsx
import { marked } from 'marked'
import { useEffect, useState } from 'react'

interface InlineMarkdownProps {
  content: string
  className?: string
}

export function InlineMarkdown({ content, className = '' }: InlineMarkdownProps) {
  const [html, setHtml] = useState('')

  useEffect(() => {
    // Render markdown to HTML (inline) - simple approach
    const renderInlineMarkdown = (text: string) => {
      if (!text || typeof text !== 'string') return ''

      try {
        // Use marked synchronously by accessing the default export directly
        const result = marked.parse(text, {
          async: false,
          breaks: false,
          gfm: true,
        })

        // Strip paragraph tags for inline rendering (exact same as Svelte)
        if (typeof result === 'string') {
          return result.replace(/<\/?p>/g, '')
        }

        return ''
      } catch (e) {
        console.error('Markdown rendering error:', e)
        return text // Fallback to plain text
      }
    }

    // Set the rendered HTML
    setHtml(renderInlineMarkdown(content))
  }, [content])

  const spanClassName = className ? `inline-markdown ${className}` : 'inline-markdown'

  return (
    <span className={spanClassName} dangerouslySetInnerHTML={{ __html: html }} />
  )
}
